### ISSUE TITLE
Handle edges of viewport

### ISSUE THREAD

**Issue by Juchar** [vaadin-component-factory/vcf-popup#1]
If one scrolls to the bottom of the screen the popup currently still opens downwards. 
By consequence it will be partly invisible. 

Such cases should be recognized (also the other edges of the viewport, left, right) and the popup opened possibly in the other direction.

**Comment by TatuLund** [comment]
This has been fixed in v1.2.1 by https://github.com/vaadin-component-factory/vcf-popup/commit/095ec6c20b322ea4e850bca0e5546745a2a24250
