### ISSUE TITLE
Does not work with Vaadin 14.1+

### ISSUE THREAD

**Issue by mkn1988** [vaadin-component-factory/vcf-popup#5]
Currently the vcf-popup has a dependency towards org.webjars.bowergithub.vaadin:vaadin-element-mixin:jar:[1.0.1,2). Vaadin 14.1+ uses version 2+ of the mixin, such that maven can't build the project due to a version conflict (vcf-popup requires 1.x).

If you fix this please update the vaadin-popup as well, I currently use version 2.1.2.

**Comment by TatuLund** [comment]
This has been fixed in version Popup 2.1.3 and the latest version of the web-component.
