### ISSUE TITLE
Popup is opened below visible area if near the bottom of the viewport

### ISSUE THREAD

**Issue by mlopezFC** [vaadin-component-factory/vcf-popup#6]
See this animated gif:
![popupissue](https://user-images.githubusercontent.com/28312758/72824326-d7481900-3c53-11ea-9cc8-0af83e4d58bd.gif)

The expected behavior should be that the popup should open bottom up so the contents can be shown.

**Comment by TatuLund** [comment]
This has been fixed by https://github.com/vaadin-component-factory/vcf-popup/commit/095ec6c20b322ea4e850bca0e5546745a2a24250 The online demo app still has the old version though.
