### ISSUE TITLE
Improve the position of the overlay

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-component-factory/vcf-popup#7]
Current the position of the popup does not work well:
* On mobile (_phone is not used)
* When the overlay has not enough space on the bottom or on the right

This function:
https://github.com/vaadin-component-factory/vcf-popup/blob/polymer-3/src/vcf-popup.js#L145
could be replaced by something like this:
https://github.com/vaadin/vaadin-date-picker/blob/master/src/vaadin-date-picker-mixin.js#L644

It also doesn't follow the input when the window is resized like the date-picker-overlay.

**Comment by TatuLund** [comment]
> On mobile (_phone is not used)

I did other fixes and at the same time added the backdrop style when used on mobile.

**Comment by bwajtr** [comment]
Improved positioning and resizing in version 23.3.0
Using bottom drawer when on mobile - this functionality was lost some years ago by mistake when migrating to Polymer 3
